### ISSUE TITLE
As a MacroMaker user I want to use a keyboard shortcut to start/stop recording so that my recorded session won't be affected by opening MacroMaker window

### ISSUE THREAD

**Issue by wcomnisky** [fwcd/MacroMaker#2]
I would like to record a 6-steps mouse click macro in a fullscreen app and then play it on MacroMaker for 50 times.

Currently that is not possible as after the last step I had to switch to MacroMaker window (using Alt+Tab) to stop the recording and this will also be recorded as a macro in my MacroMaker session making it not possible to reproduce the recorded session more than once. 

Would be good to have a keyboard shortcut (customisable key combination) to start/stop the recording so the case above would be possible.

**Comment by fwcd** [comment]
I will look into that. Glad to see that someone actually found this little tool useful :)
